vim.cmd('iabbrev serialziers serializers')
vim.cmd('iabbrev reponse response')
vim.cmd('iabbrev profesion profession')
vim.cmd('iabbrev professsion profession')
vim.cmd('iabbrev profesions professions')
vim.cmd('iabbrev professsions professions')
