return {
  -- Yet another tree-sitter indent plugin for Neovim.
  { "yioneko/nvim-yati", event = "InsertEnter" },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "diff",
        "fish",
        "gitignore",
        "vimdoc",
        "html",
        "http",
        "javascript",
        "lua",
        "jsonc",
        "json5",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "rust",
        "sql",
        "toml",
        "vim",
        "yaml",
        "json",
        "gitcommit",
        "rst",
        "tsx",
        "typescript",
      },
      highlight = { enable = true },
      indent = { enable = false },
      yati = {
        enable = true,
        default_lazy = true,
        default_fallback = "auto",
      },
      query_linter = {
        enable = true,
        use_virtual_text = true,
        lint_events = { "BufWrite", "CursorHold" },
      },
    },
  },
}
