require('packer_init')
require('core/options')
require('core/autocmds')
require('core/keymaps')
require('core/abbrev')

require('plugins/indent-blankline')
require('plugins/move')
require('plugins/null-ls')
require('plugins/treesitter')
require('plugins/mason-lspconfig.lua')
require('plugins/mason-tool-installer.lua')
require('plugins/catppuccin')
